import Head from "next/head";
// import Image from 'next/image'
// import Login from "./login";
import Themes from "./themes"



export default function Home() {
  return (
    <div >
      <Head>
        <title>Live Tree</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Login/> */}
      <Themes/>


    </div>
  )
}
